#
# Your Crowdin credentials
#
"project_id" : "24"
"api_token_env" : "CROWDIN_ALMA_TOKEN"
"base_path" : "."
"base_url" : "https://almapay.crowdin.com"
"preserve_hierarchy": true

files: [
  {
    "source" : "/cartridges/int_alma/cartridge/templates/resources/alma.properties",
    "translation" : "/cartridges/int_alma/cartridge/templates/resources/alma_%locale_with_underscore%.properties",
  },
  {
    "source" : "/site_preference_builder/messages.js",
    "translation" : "/site_preference_builder/messages-%locale_with_underscore%.js",
  }
]
